# Generated by Django 4.0.10 on 2023-04-24 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Administratornummer')),
                ('email', models.EmailField(max_length=250, verbose_name='E-mailadres')),
                ('last_name', models.CharField(max_length=250, verbose_name='Achternaam')),
                ('first_name', models.CharField(max_length=250, verbose_name='Voornaam')),
                ('is_admin', models.BooleanField(default=True, verbose_name='Is administrator')),
            ],
        ),
        migrations.CreateModel(
            name='McQuestion',
            fields=[
                ('mc_question_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Vraagnummer')),
                ('question', models.CharField(max_length=250, verbose_name='Vragen')),
                ('option_a', models.CharField(max_length=250, verbose_name='Optie A')),
                ('option_b', models.CharField(max_length=250, verbose_name='Optie B')),
                ('option_c', models.CharField(blank=True, default='', max_length=250, verbose_name='Optie C')),
                ('option_d', models.CharField(blank=True, default='', max_length=250, verbose_name='Optie D')),
            ],
            options={
                'verbose_name': 'Meerkeuzevraag',
                'verbose_name_plural': 'Meerkeuzevragen',
            },
        ),
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('open_question_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Vraagnummer')),
                ('question', models.CharField(max_length=250, verbose_name='Vragen')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Verbergen')),
            ],
            options={
                'verbose_name': 'Open vraag',
                'verbose_name_plural': 'Open vragen',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('team_member_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Teamlidnummer')),
                ('email', models.EmailField(max_length=250, verbose_name='E-mailadres')),
                ('last_name', models.CharField(max_length=250, verbose_name='Achternaam')),
                ('first_name', models.CharField(max_length=250, verbose_name='Voornaam')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is administrator')),
            ],
            options={
                'verbose_name': 'Teamlid',
                'verbose_name_plural': 'Teamleden',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Enquêtenummer')),
                ('title', models.CharField(max_length=100, verbose_name='Naam enquête')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Toelichting')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anonieme respons')),
                ('date_sent', models.DateField(null=True, verbose_name='Verzonden op')),
                ('url', models.URLField(default='', unique=True)),
                ('admin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ccforms.administrator', verbose_name='Administrator')),
                ('mc_question', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ccforms.mcquestion', verbose_name='Meerkeuzevragen')),
                ('open_question', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ccforms.openquestion', verbose_name='Open vragen')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Responsnummer')),
                ('date_submitted', models.DateField(null=True, verbose_name='Ingevuld op')),
                ('mc_question', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ccforms.mcquestion', verbose_name='Meerkeuzevragen')),
                ('open_question', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ccforms.openquestion', verbose_name='Open vragen')),
                ('survey', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ccforms.survey', verbose_name='Naam enquête')),
                ('tm_email', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ccforms.teammember', verbose_name='E-mailadres teamlid')),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Itemnummer')),
                ('mc_question', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ccforms.mcquestion', verbose_name='Meerkeuzevragen')),
                ('open_question', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ccforms.openquestion', verbose_name='Open vragen')),
                ('response', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ccforms.response', verbose_name='Reacties')),
                ('survey', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ccforms.survey', verbose_name='Naam enquête')),
                ('tm_email', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ccforms.teammember', verbose_name='E-mailadres teamlid')),
            ],
            options={
                'verbose_name_plural': 'Archive',
            },
        ),
    ]
