# Generated by Django 4.0.9 on 2023-04-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcquestion',
            options={'verbose_name': 'Multiple Choice Question'},
        ),
    ]
