# Generated by Django 4.2 on 2023-05-01 12:01

from django.db import migrations


# create_data functie maakt initiële data aan, zodat de database
# niet leeg is als de API wordt gestart.
def create_data(apps, schema_editor):
    student = apps.get_model('students', 'student')
    student(
        name="Joe Silver",
        email="joe@email.com",
        document="22342342",
        phone="00000000"
    ).save()


class Migration(migrations.Migration):

    # Zorgt dat de initial file wordt meegenomen in het migratieproces
    dependencies = [
        ('students', '0001_initial'),
    ]

    # Acties die Django moet ondernemen zodra de migratie wordt gestart.
    operations = [
        migrations.RunPython(create_data),
    ]
