# Generated by Django 4.0.9 on 2023-06-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccforms', '0002_alter_survey_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='tm_email',
            field=models.CharField(max_length=100, verbose_name='Naam enquête'),
        ),
    ]
