# Generated by Django 4.0.10 on 2023-05-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccforms', '0002_remove_survey_question_survey_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiplechoice',
            options={'verbose_name': 'Meerkeuzeoptie', 'verbose_name_plural': 'Meerkeuzeopties'},
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='question',
            new_name='questions',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.AddField(
            model_name='response',
            name='answers',
            field=models.ManyToManyField(to='ccforms.question', verbose_name='Antwoorden'),
        ),
        migrations.AddField(
            model_name='response',
            name='multiple_choice',
            field=models.ManyToManyField(to='ccforms.multiplechoice', verbose_name='Meerkeuzeopties'),
        ),
        migrations.AddField(
            model_name='survey',
            name='multiple_choice',
            field=models.ManyToManyField(to='ccforms.multiplechoice', verbose_name='Meerkeuzeopties'),
        ),
    ]
