# Generated by Django 4.0.10 on 2023-05-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccforms', '0003_alter_multiplechoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='admin_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ccforms.question', verbose_name='Vraag'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='multiple_choice',
            field=models.ManyToManyField(to='ccforms.multiplechoice', verbose_name='Meerkeuzevragen'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(to='ccforms.question', verbose_name='Open vragen'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team_member_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
