# Generated by Django 4.0.9 on 2023-06-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccforms', '0003_alter_response_tm_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='url',
            field=models.CharField(max_length=300, verbose_name='Link'),
        ),
    ]
